# Generated by Django 4.2.8 on 2025-05-17 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CancerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField()),
                ("symptoms", models.TextField()),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Rendah"),
                            ("MEDIUM", "Sedang"),
                            ("HIGH", "Tinggi"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CauseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Cause Categories",
            },
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("side_effects", models.TextField()),
                ("success_rate", models.CharField(blank=True, max_length=100)),
                (
                    "treatment_type",
                    models.CharField(
                        choices=[
                            ("SURGERY", "Operasi"),
                            ("RADIATION", "Terapi Radiasi"),
                            ("CHEMOTHERAPY", "Kemoterapi"),
                            ("IMMUNOTHERAPY", "Imunoterapi"),
                            ("TARGETED", "Terapi Target"),
                            ("HORMONE", "Terapi Hormon"),
                            ("STEM_CELL", "Transplantasi Sel Induk"),
                            ("ALTERNATIVE", "Terapi Alternatif"),
                            ("OTHER", "Lainnya"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "cancer_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatments",
                        to="cancer_app.cancertype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(default="default.jpg", upload_to="profile_pics"),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prevention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "effectiveness",
                    models.CharField(
                        choices=[
                            ("LOW", "Rendah"),
                            ("MEDIUM", "Sedang"),
                            ("HIGH", "Tinggi"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "cancer_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preventions",
                        to="cancer_app.cancertype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "risk_factor",
                    models.FloatField(default=1.0, help_text="Faktor risiko relatif"),
                ),
                (
                    "cancer_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="causes",
                        to="cancer_app.cancertype",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="causes",
                        to="cancer_app.causecategory",
                    ),
                ),
            ],
        ),
    ]
